/**
 * Gitignore management — per-target .gitignore files.
 *
 * Each output boundary gets its own .gitignore with paths relative to that
 * directory. Tool outputs use the tool directory (e.g., .claude/, .cursor/),
 * while root-level outputs use the project/global root. This ensures:
 *
 *  - All artifacts are ignored regardless of activation state
 *  - Global scope is supported (same mechanism, absolute target dirs)
 *  - The project root .gitignore only contains root-level managed outputs
 *
 * Gitignore is part of the artifact lifecycle (add/delete/import), not the
 * render pipeline. Updates happen when artifacts are created or removed,
 * not when loadouts are activated or synced.
 *
 * Uses markers to identify the managed section:
 *   # <loadouts>
 *   ...managed paths...
 *   # </loadouts>
 */

import * as path from "node:path";
import * as os from "node:os";
import {
  fileExists,
  readFile,
  writeFile,
  listFiles,
  isDirectory,
} from "./fs.js";
import { registry } from "../core/registry.js";
import { getBundledRoot } from "../core/discovery.js";
import { expandTemplate, type TemplateVars } from "../core/template.js";
import type { Scope } from "../core/types.js";

const START_MARKER = "# <loadouts>";
const END_MARKER = "# </loadouts>";
const HEADER_COMMENT = "# Auto-generated by loadouts. Do not edit this section.";

// Legacy markers from old naming convention
const LEGACY_START_MARKER = "# <loadout>";
const LEGACY_END_MARKER = "# </loadout>";

// Paths always ignored within .loadouts/
const LOADOUTS_STATE_PATHS = [".fallback-applied", ".state.json"];

// ---------------------------------------------------------------------------
// Core write function
// ---------------------------------------------------------------------------

/**
 * Low-level: write the managed section to a specific .gitignore file path.
 */
function updateGitignoreFile(gitignorePath: string, managedPaths: string[]): void {
  // Sort and deduplicate
  const uniquePaths = [...new Set(managedPaths)].sort();

  const managedSection =
    uniquePaths.length > 0
      ? `${START_MARKER}\n${HEADER_COMMENT}\n${uniquePaths.join("\n")}\n${END_MARKER}`
      : "";

  if (!fileExists(gitignorePath)) {
    if (managedSection) {
      writeFile(gitignorePath, managedSection + "\n");
    }
    return;
  }

  const content = readFile(gitignorePath);
  let startIdx = content.indexOf(START_MARKER);
  let endIdx = content.indexOf(END_MARKER);
  let markerLength = END_MARKER.length;

  if (startIdx === -1 || endIdx === -1 || endIdx <= startIdx) {
    startIdx = content.indexOf(LEGACY_START_MARKER);
    endIdx = content.indexOf(LEGACY_END_MARKER);
    markerLength = LEGACY_END_MARKER.length;
  }

  if (startIdx !== -1 && endIdx !== -1 && endIdx > startIdx) {
    // Replace existing section
    const before = content.slice(0, startIdx).trimEnd();
    const after = content.slice(endIdx + markerLength).trimStart();

    const parts = [before];
    if (managedSection) parts.push(managedSection);
    if (after) parts.push(after);

    let newContent = parts.filter(Boolean).join("\n\n");
    if (!newContent.endsWith("\n")) newContent += "\n";

    writeFile(gitignorePath, newContent);
  } else {
    // No existing section — append
    if (!managedSection) return;

    let newContent = content.trimEnd();
    newContent += "\n\n" + managedSection + "\n";
    writeFile(gitignorePath, newContent);
  }
}

// ---------------------------------------------------------------------------
// Public write functions
// ---------------------------------------------------------------------------

/**
 * Update .gitignore within a specific target directory.
 *
 * @param targetDir - Absolute path to the target directory (e.g., /project/.claude or ~/.claude)
 * @param relativePaths - Paths relative to targetDir (e.g., ["rules/foo.md", "skills/bar/"])
 */
export function updateTargetGitignore(
  targetDir: string,
  relativePaths: string[]
): void {
  updateGitignoreFile(path.join(targetDir, ".gitignore"), relativePaths);
}

/**
 * Update .loadouts/.gitignore with state file entries.
 * Always includes .state.json and .fallback-applied.
 */
export function updateLoadoutsGitignore(loadoutsDir: string): void {
  updateGitignoreFile(path.join(loadoutsDir, ".gitignore"), LOADOUTS_STATE_PATHS);
}

// ---------------------------------------------------------------------------
// Path computation
// ---------------------------------------------------------------------------

/**
 * Compute gitignore paths for an artifact, grouped by gitignore directory.
 *
 * Returns a Map of gitignore base directory → relative paths within that
 * directory. Outputs under a tool base use that tool base. Outputs outside the
 * tool base (for example AGENTS.md or opencode.jsonc at project root) use the
 * project/global root.
 */
export function computeArtifactGitignorePaths(
  kindId: string,
  artifactName: string,
  scope: Scope = "project"
): Map<string, string[]> {
  const kind = registry.getKind(kindId);
  if (!kind) return new Map();

  const relativePath = synthesizeArtifactRelativePath(kindId, artifactName, kind.layout);
  const sourcePath = path.join(os.tmpdir(), "loadouts-gitignore", relativePath);
  return computeSourceArtifactGitignorePaths(kindId, relativePath, sourcePath, scope);
}

function computeSourceArtifactGitignorePaths(
  kindId: string,
  relativePath: string,
  sourcePath: string,
  scope: Scope
): Map<string, string[]> {
  const kind = registry.getKind(kindId);
  if (!kind) return new Map();

  const byTarget = new Map<string, string[]>();

  for (const tool of registry.allTools()) {
    const mapping = registry.resolveMapping(tool.name, kindId);
    if (!mapping) continue;

    const targetBase = tool.basePath[scope];
    const sourceExt = path.extname(sourcePath);
    const ext = mapping.ext ?? sourceExt;

    const vars: TemplateVars = {
      base: targetBase,
      home: os.homedir(),
      stem: path.basename(sourcePath, sourceExt),
      ext,
      name: path.basename(sourcePath),
      relative: relativePath,
      kind: kindId,
    };

    const pathTemplate =
      typeof mapping.path === "string" ? mapping.path : mapping.path[scope];

    try {
      const expandedPath = expandTemplate(pathTemplate, scope, vars);
      const target = getGitignoreTarget(expandedPath, targetBase, scope);
      if (!target) continue;

      const existing = byTarget.get(target.base) ?? [];

      if (kind.layout === "dir") {
        // Dir-layout: use trailing slash so all files within are covered
        existing.push(target.relativePath.endsWith("/") ? target.relativePath : target.relativePath + "/");
      } else {
        existing.push(target.relativePath);
      }

      byTarget.set(target.base, existing);
    } catch {
      // Skip if template expansion fails
    }
  }

  return byTarget;
}

// ---------------------------------------------------------------------------
// Rebuild
// ---------------------------------------------------------------------------

/**
 * Rebuild gitignore entries for all artifacts in the loadouts directory.
 *
 * Scans all artifacts and writes per-target .gitignore files so that
 * every artifact is ignored regardless of whether it is currently activated.
 * Called after artifact add/delete/import.
 *
 * @param loadoutsDir  - Absolute path to .loadouts/ or ~/.config/loadouts/
 * @param projectRoot  - Project root for resolving relative target paths
 *                       (unused for global scope since all paths are absolute)
 * @param scope        - "project" or "global"
 */
export function rebuildAllGitignores(
  loadoutsDir: string,
  projectRoot: string,
  scope: Scope
): void {
  const allByTarget = collectArtifactPathsByTarget(loadoutsDir, scope);

  // Ensure all relevant target dirs are updated, even when they now have no
  // managed artifacts. This removes stale managed sections from previous runs.
  const managedTargets = new Set<string>([
    ...getManagedTargetBases(scope),
    ...allByTarget.keys(),
  ]);

  for (const targetBase of managedTargets) {
    const paths = allByTarget.get(targetBase) ?? [];
    const absTargetDir = path.isAbsolute(targetBase)
      ? targetBase
      : path.join(projectRoot, targetBase);
    updateTargetGitignore(absTargetDir, paths);
  }
}

export interface TargetGitignoreMismatch {
  targetDir: string;
  expectedPaths: string[];
  actualPaths: string[];
}

export interface GitignoreHealthReport {
  hasLegacyRootSection: boolean;
  loadoutsStateOutOfDate: boolean;
  targetMismatches: TargetGitignoreMismatch[];
  issues: number;
}

/**
 * Check whether the legacy managed section exists in root .gitignore.
 * Handles both # <loadouts> and older # <loadout> markers.
 */
export function hasLegacyRootGitignoreSection(projectRoot: string): boolean {
  const gitignorePath = path.join(projectRoot, ".gitignore");
  if (!fileExists(gitignorePath)) return false;

  const content = readFile(gitignorePath);
  return (
    hasMarkerSection(content, START_MARKER, END_MARKER) ||
    hasMarkerSection(content, LEGACY_START_MARKER, LEGACY_END_MARKER)
  );
}

/**
 * Inspect gitignore state for a scope and report drift from expected state.
 */
export function inspectGitignoreHealth(
  loadoutsDir: string,
  projectRoot: string,
  scope: Scope
): GitignoreHealthReport {
  const expectedByTarget = collectArtifactPathsByTarget(loadoutsDir, scope);

  const targetBases = new Set<string>([
    ...getManagedTargetBases(scope),
    ...expectedByTarget.keys(),
  ]);

  const targetMismatches: TargetGitignoreMismatch[] = [];
  for (const targetBase of [...targetBases].sort()) {
    const absTargetDir = path.isAbsolute(targetBase)
      ? targetBase
      : path.join(projectRoot, targetBase);

    const expectedPaths = normalizePaths(expectedByTarget.get(targetBase) ?? []);
    const actualPaths = normalizePaths(getManagedPathsFromTarget(absTargetDir));

    if (!samePaths(expectedPaths, actualPaths)) {
      targetMismatches.push({
        targetDir: absTargetDir,
        expectedPaths,
        actualPaths,
      });
    }
  }

  const expectedStatePaths = normalizePaths(LOADOUTS_STATE_PATHS);
  const actualStatePaths = normalizePaths(getManagedPathsFromTarget(loadoutsDir));
  const loadoutsStateOutOfDate = !samePaths(expectedStatePaths, actualStatePaths);

  const hasLegacyRootSection = hasOldRootGitignoreSection(projectRoot);

  const issues =
    targetMismatches.length +
    (loadoutsStateOutOfDate ? 1 : 0) +
    (hasLegacyRootSection ? 1 : 0);

  return {
    hasLegacyRootSection,
    loadoutsStateOutOfDate,
    targetMismatches,
    issues,
  };
}

// ---------------------------------------------------------------------------
// Read helpers
// ---------------------------------------------------------------------------

/**
 * Get the current managed paths from a target directory's .gitignore.
 */
export function getManagedPathsFromTarget(targetDir: string): string[] {
  return getManagedPathsFromFile(path.join(targetDir, ".gitignore"));
}

function getManagedPathsFromFile(gitignorePath: string): string[] {
  if (!fileExists(gitignorePath)) return [];

  const content = readFile(gitignorePath);
  const startIdx = content.indexOf(START_MARKER);
  const endIdx = content.indexOf(END_MARKER);

  if (startIdx === -1 || endIdx === -1 || endIdx <= startIdx) return [];

  const section = content.slice(startIdx + START_MARKER.length, endIdx);
  return section
    .split("\n")
    .map((line) => line.trim())
    .filter((line) => line && !line.startsWith("#"));
}

// ---------------------------------------------------------------------------
// Migration helper
// ---------------------------------------------------------------------------

/**
 * Remove the legacy loadouts-managed section from the project root .gitignore.
 * Handles both old (# <loadout>) and current (# <loadouts>) markers.
 * Used by the `update` command to migrate from the old single-file approach.
 */
export function removeLegacyRootGitignoreSection(projectRoot: string): void {
  const gitignorePath = path.join(projectRoot, ".gitignore");
  if (!fileExists(gitignorePath)) return;

  let content = readFile(gitignorePath);

  // Remove both new and old marker sections
  content = removeMarkerSection(content, START_MARKER, END_MARKER);
  content = removeMarkerSection(content, LEGACY_START_MARKER, LEGACY_END_MARKER);

  // Clean up excess blank lines
  content = content.replace(/\n{3,}/g, "\n\n").trimEnd();
  if (content) content += "\n";

  writeFile(gitignorePath, content || "");
}

// ---------------------------------------------------------------------------
// Internal utilities
// ---------------------------------------------------------------------------

function removeMarkerSection(
  content: string,
  startMarker: string,
  endMarker: string
): string {
  const startIdx = content.indexOf(startMarker);
  const endIdx = content.indexOf(endMarker);

  if (startIdx === -1 || endIdx === -1 || endIdx <= startIdx) return content;

  const before = content.slice(0, startIdx).trimEnd();
  const after = content.slice(endIdx + endMarker.length).trimStart();

  if (before && after) return before + "\n\n" + after;
  return before || after;
}

function hasMarkerSection(
  content: string,
  startMarker: string,
  endMarker: string
): boolean {
  const startIdx = content.indexOf(startMarker);
  const endIdx = content.indexOf(endMarker);
  return startIdx !== -1 && endIdx !== -1 && endIdx > startIdx;
}

function hasOldRootGitignoreSection(projectRoot: string): boolean {
  const gitignorePath = path.join(projectRoot, ".gitignore");
  if (!fileExists(gitignorePath)) return false;

  const content = readFile(gitignorePath);
  return hasMarkerSection(content, LEGACY_START_MARKER, LEGACY_END_MARKER);
}

function collectArtifactPathsByTarget(
  loadoutsDir: string,
  scope: Scope
): Map<string, string[]> {
  const allByTarget = new Map<string, string[]>();

  const roots = [loadoutsDir, ...getSupplementalArtifactRoots(loadoutsDir, scope)];

  for (const root of roots) {
    for (const artifact of collectArtifacts(root)) {
      mergeIntoMap(
        allByTarget,
        computeSourceArtifactGitignorePaths(
          artifact.kindId,
          artifact.relativePath,
          artifact.sourcePath,
          scope
        )
      );
    }
  }

  return allByTarget;
}

function getSupplementalArtifactRoots(loadoutsDir: string, scope: Scope): string[] {
  // Bundled artifacts should contribute to global ignore expectations when
  // global loadouts are managed from ~/.config/loadouts.
  if (scope !== "global") return [];
  if (!isGlobalLoadoutsDir(loadoutsDir)) return [];

  const bundled = getBundledRoot();
  if (!bundled) return [];
  return [bundled.path];
}

function isGlobalLoadoutsDir(loadoutsDir: string): boolean {
  const expected = path.resolve(os.homedir(), ".config", "loadouts");
  return path.resolve(loadoutsDir) === expected;
}

function getManagedTargetBases(scope: Scope): string[] {
  const bases = new Set<string>([getRootGitignoreBase(scope)]);
  for (const tool of registry.allTools()) {
    bases.add(tool.basePath[scope]);
  }
  return [...bases];
}

interface ArtifactRef {
  kindId: string;
  relativePath: string;
  sourcePath: string;
}

function collectArtifacts(loadoutsDir: string): ArtifactRef[] {
  const artifacts: ArtifactRef[] = [];

  function walk(relativeDir: string): void {
    const absDir = path.join(loadoutsDir, relativeDir);

    for (const entry of listFiles(absDir).sort()) {
      const relativePath = relativeDir ? path.join(relativeDir, entry) : entry;
      const sourcePath = path.join(loadoutsDir, relativePath);

      if (isDirectory(sourcePath)) {
        const kindId = registry.inferKind(relativePath);
        const kind = kindId ? registry.getKind(kindId) : undefined;
        if (kindId && kind?.layout === "dir") {
          artifacts.push({ kindId, relativePath, sourcePath });
          continue;
        }

        walk(relativePath);
        continue;
      }

      const kindId = registry.inferKind(relativePath);
      const kind = kindId ? registry.getKind(kindId) : undefined;
      if (kindId && kind?.layout === "file") {
        artifacts.push({ kindId, relativePath, sourcePath });
      }
    }
  }

  walk("");
  return artifacts;
}

function synthesizeArtifactRelativePath(
  kindId: string,
  artifactName: string,
  layout: "file" | "dir"
): string {
  if (kindId === "rule") return `rules/${artifactName}.md`;
  if (kindId === "skill") return `skills/${artifactName}`;
  if (kindId === "instruction") return `instructions/${artifactName}.md`;
  if (kindId === "prompt") return `prompts/${artifactName}.md`;
  if (kindId === "extension") return `extensions/${withDefaultExtension(artifactName, ".ts")}`;
  if (kindId === "theme") return `themes/${withDefaultExtension(artifactName, ".json")}`;
  if (kindId === "opencode-config") return `opencode/${withDefaultExtension(artifactName, ".jsonc")}`;
  if (kindId === "opencode-tui-config") return `opencode/${withDefaultExtension(artifactName, ".jsonc")}`;
  if (kindId === "opencode-plugin") return `opencode/plugins/${withDefaultExtension(artifactName, ".ts")}`;
  return layout === "dir" ? `${kindId}s/${artifactName}` : `${kindId}s/${artifactName}.md`;
}

function withDefaultExtension(name: string, ext: string): string {
  return path.extname(name) ? name : `${name}${ext}`;
}

interface GitignoreTarget {
  base: string;
  relativePath: string;
}

function getGitignoreTarget(
  targetPath: string,
  toolBase: string,
  scope: Scope
): GitignoreTarget | null {
  const normalizedTarget = path.normalize(targetPath);
  const normalizedBase = path.normalize(toolBase);
  const relativeToToolBase = path.relative(normalizedBase, normalizedTarget);

  if (
    relativeToToolBase &&
    !relativeToToolBase.startsWith("..") &&
    !path.isAbsolute(relativeToToolBase)
  ) {
    return { base: toolBase, relativePath: relativeToToolBase };
  }

  if (!path.isAbsolute(normalizedTarget)) {
    return {
      base: getRootGitignoreBase(scope),
      relativePath: normalizedTarget,
    };
  }

  return {
    base: path.dirname(normalizedTarget),
    relativePath: path.basename(normalizedTarget),
  };
}

function getRootGitignoreBase(scope: Scope): string {
  return scope === "project" ? "." : os.homedir();
}

function normalizePaths(paths: string[]): string[] {
  return [...new Set(paths)].sort();
}

function samePaths(a: string[], b: string[]): boolean {
  if (a.length !== b.length) return false;
  for (let i = 0; i < a.length; i++) {
    if (a[i] !== b[i]) return false;
  }
  return true;
}

function mergeIntoMap(
  target: Map<string, string[]>,
  source: Map<string, string[]>
): void {
  for (const [key, values] of source) {
    const existing = target.get(key) ?? [];
    target.set(key, [...existing, ...values]);
  }
}

// ---------------------------------------------------------------------------
// Deprecated — kept for migration use in update.ts
// ---------------------------------------------------------------------------

/**
 * @deprecated Use getManagedPathsFromTarget instead.
 * Still used by the update command to detect whether migration is needed.
 */
export function getManagedPaths(projectRoot: string): string[] {
  return getManagedPathsFromFile(path.join(projectRoot, ".gitignore"));
}
